apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: barebone-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-backend
        image: iyusuf/fastapi-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
  namespace: barebone-html
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 8080          # The port that the Service will expose (pod port)
      targetPort: 8000  # The port on the container to which the Service should forward traffic
      nodePort: 30099
  type: NodePort
