---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fastapiBackend.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.fastapiBackend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.fastapiBackend.servicePort }}
      targetPort: {{ .Values.fastapiBackend.containerPort }}
  type: ClusterIP
