apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgDb.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.pgDb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.pgDb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgDb.name }}
    spec:
      containers:
      - name: {{ .Values.pgDb.containerName }}
        image: {{ .Values.pgDb.image.repository }}:{{ .Values.pgDb.image.tag }}
        ports:
        - containerPort: {{ .Values.pgDb.containerPort }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.pgDb.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.pgDb.env.POSTGRES_PASSWORD }}
        - name: POSTGRES_DB
          value: {{ .Values.pgDb.env.POSTGRES_DB }}
