apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgDb.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.pgDb.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.pgDb.servicePort }}
      targetPort: {{ .Values.pgDb.containerPort }}
  type: ClusterIP
