apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webServer.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.webServer.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.webServer.servicePort }}
      targetPort: {{ .Values.webServer.containerPort }}
      nodePort: {{ .Values.webServer.nodePort }}
  type: NodePort
