apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server1
  namespace: barebone-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server1
  template:
    metadata:
      labels:
        app: web-server1
    spec:
      containers:
      - name: web-server1
        image: iyusuf/web-server1-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-server1-service
  namespace: barebone-html
spec:
  selector:
    app: web-server1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
