apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  namespace: tinyweb3tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-db
  template:
    metadata:
      labels:
        app: pg-db
    spec:
      containers:
      - name: pg-db
        image: iyusuf/dbserver:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "myuser"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: pg-db-service
  namespace: tinyweb3tier
spec:
  selector:
    app: pg-db
  ports:
    - protocol: TCP
      port: 5432      # The port that the Service will expose
      targetPort: 5432 # The port on the container to which the Service should forward traffic
  type: ClusterIP
